POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "fullName":"Freddy Michel",
    "username":"Freddymi",
    "email":"michelfreddy1992@gmail.com",
    "password":"FreddyMi2123"
}